[project]
org-name= "admin"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "mysql-connector-java"
    version = "5.1.45"
    path = "./libs/mysql-connector-java-5.1.45.jar"
    groupId = "mysql"
    modules = ["registry_admin_api"]
